spring.application.name=agendamento-api

spring.datasource.url=jdbc:mysql://localhost:3306/barbearia_db
spring.datasource.username=barbeiro
spring.datasource.password=senha123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:b7ArjS8kL2pQwZxV9mNcYt4RhU6eFgD1oIiKjXsWnBv3TlEr}
jwt.expiration=36000000